### ISSUE TITLE
サインアップで送られてきたメールのURLにアクセスすると「無効なリンクです。メールの内容をもう一度確認してください」と表示される

### ISSUE THREAD

**Issue by nobiinu-and** [agilecommunity/oot#102]
法則はない感じ。

**Comment by nobiinu-and** [comment]
deleteExpiredTokens の処理に問題があるらしく、保存期間を超えてないデータを削除しているっぽい。

**Comment by masayukig** [comment]
多分、私が理解してないだけだと思いますが、
https://github.com/agilecommunity/oot/blob/master/app/services/UserService.java#L138
で、
`new DateTime().toString()`と、toString()しているのはなぜなんでしょうか？
文字列で大小比較しているようにも見えますが。

**Comment by hideakihal** [comment]
PRを出しておいたので確認お願いします。

**Comment by nobiinu-and** [comment]
PRにコメントしました、追加して再度PRします

**Comment by nobiinu-and** [comment]
日付にTimezoneを付けようとしていろいろいじった結果、修正範囲がばかみたいに広くなった…orz

**Comment by nobiinu-and** [comment]
TravisCIで、タイムゾーン変えてもちゃんと動くかテストしたくなってきたwww
