### ISSUE TITLE
アプリのバージョンが分かるようにしたい

### ISSUE THREAD

**Issue by nobiinu-and** [agilecommunity/oot#112]
アップデートが増えそうなので、バージョンが分からないと混乱する…気がする。

**Comment by nobiinu-and** [comment]
まぁ半分趣味みたいなもんだけど。
Subversionだとリビジョンの情報使うのが楽なんだけど、Gitの場合もそれでいけるのかな?
で、それはいったいいつどうやって作るんだろう??

**Comment by nobiinu-and** [comment]
git describe でバージョン情報を生成できるようだ。
けど、タグ作らないといけない。

マイルストーンのIssueが全部終了したら、マイルストーンで設定したバージョンになると決めると、
今は 0.1 の前だから、バージョン 0.0 にするか。(なんかひどい気もするけど)

f76d4cb425d8941e46b66700b3ad23a7642a9fa8 で0.0が終わったことにしよう。

**Comment by masayukig** [comment]
0.0.1とかにしたらどうでしょうか？
もう、遅いかもしれませんが。

**Comment by nobiinu-and** [comment]
おー。よかった。まだローカルなのでなんとかなるんじゃないかと思われます。

**Comment by nobiinu-and** [comment]
0.0.1にして、git describe してみた。

v0.0.1-17-g09cc139

と表示される。0.1の開発中とは分からないけど、まぁいいか?

**Comment by nobiinu-and** [comment]
app-info.yaml に以下のように書いておくと、
    version: v0.0.1-17-g09cc139
プログラム上で、アプリケーションのバージョンが取り出せるってことにする。

**Comment by nobiinu-and** [comment]
app-meta.yaml の方がいいかな?

**Comment by nobiinu-and** [comment]
運用は、conf/app-meta.yaml にファイルを作った後、 play dist で固めればOKのハズ。
