### ISSUE TITLE
パスワードのリセットができるようにしたい

### ISSUE THREAD

**Issue by masayukig** [agilecommunity/oot#27]
<a href="https://github.com/nobiinu-and"><img src="https://avatars.githubusercontent.com/u/920978?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nobiinu-and](https://github.com/nobiinu-and)**
_Mon Sep 15 12:16:46 2014_
_Originally opened as https://github.com/nobiinu-and/oot/issues/27_

----

そういえば忘れてた…

**Comment by nobiinu-and** [comment]
#99 と重複。
