### ISSUE TITLE
Play Frameworkを2.3.8にする

### ISSUE THREAD

**Issue by masayukig** [agilecommunity/oot#28]
<a href="https://github.com/nobiinu-and"><img src="https://avatars.githubusercontent.com/u/920978?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nobiinu-and](https://github.com/nobiinu-and)**
_Fri Sep 19 12:19:17 2014_
_Originally opened as https://github.com/nobiinu-and/oot/issues/28_

----

#23 関連。2.3.4にすると、Configurationでunderlyingとか使って、
設定の動的変更がしやすいんじゃないかとよそう。

いつまでも2.2.xなのもなんだし。

**Comment by nobiinu-and** [comment]
2.3.8になっておりました。
