### ISSUE TITLE
注文すると、注文中のロゴに隠れて、商品名が見えなくなってしまう

### ISSUE THREAD

**Issue by masayukig** [agilecommunity/oot#37]
<a href="https://github.com/nobiinu-and"><img src="https://avatars.githubusercontent.com/u/920978?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nobiinu-and](https://github.com/nobiinu-and)**
_Tue Sep 30 15:23:14 2014_
_Originally opened as https://github.com/nobiinu-and/oot/issues/37_

----

**Comment by nobiinu-and** [comment]
注文中ロゴより、お弁当の画像が小さい場合にゆかいなことになってしまうので、再度オープン。
最小の高さを指定したほうがよさそうだ。
