### ISSUE TITLE
ログアウトができるようにする

### ISSUE THREAD

**Issue by masayukig** [agilecommunity/oot#47]
<a href="https://github.com/nobiinu-and"><img src="https://avatars.githubusercontent.com/u/920978?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nobiinu-and](https://github.com/nobiinu-and)**
_Wed Nov  5 08:19:35 2014_
_Originally opened as https://github.com/nobiinu-and/oot/issues/47_

----

ログインしっぱなしはちょっとダサい。

securesocial.core.Authenticator インスタンスを取得して、
Authenticator.delete(authenticator.id());
でいけるらしい。
securesocial.core.Authenticator インスタンスを取得する方法は、 SecureSocial.core.SecureSocial.java を参考にすること。

**Comment by nobiinu-and** [comment]
わざわざ実装しなくても、securesocialの標準を使えばできた…orz
#28 の対応でログアウトの仕組みは組み込んだので、あとはUIを実装すればいいだけ。

出口のアイコンを名前の隣におけばいいかな?
