### ISSUE TITLE
商品の画像を登録したい

### ISSUE THREAD

**Issue by masayukig** [agilecommunity/oot#67]
<a href="https://github.com/nobiinu-and"><img src="https://avatars.githubusercontent.com/u/920978?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nobiinu-and](https://github.com/nobiinu-and)**
_Fri Nov 28 13:51:25 2014_
_Originally opened as https://github.com/nobiinu-and/oot/issues/67_

----

**Comment by nobiinu-and** [comment]
http://flabo.io/code/20141031/01-angularjs-compare-file-upload/

ngUploadか、angular-file-uploadかなぁ。個人的にはangular-file-uploadにwktkするんだけども。
Flash入れる必要があるっていったって、管理者だけの制限だしな。

いや、ちょっと待てよ。今後を考えると利用者側も使う可能性があるのか。うーん。

**Comment by nobiinu-and** [comment]
あれ? クリップボードで調べてた気がスルな…。

**Comment by nobiinu-and** [comment]
あれはクリップボードにコピーだった。こっちはクリップボードからコピーだ。

http://qiita.com/volpe28v@github/items/dc100c75c2371bb82a3b

が参考になりそうだけど、IE8で動くかなぁ…。

**Comment by nobiinu-and** [comment]
利用者のことは考えない。管理者の人にはFirefoxかChrome入れてもらう。
ってことで、クリップボードから画像貼り付けられるようにしてみよう。

**Comment by nobiinu-and** [comment]
http://stackoverflow.com/questions/15253468/get-pasted-image-from-clipboard-firefox

このコードがFirefoxで動いたので、これでやってみよう。

**Comment by nobiinu-and** [comment]
動き的には何とかできた。
今のところFirefoxのみだけど、結構便利だし、いいんじゃないかな? IE8はここはあきらめよう…。
