### ISSUE TITLE
チェックリスト画面で金額が2重で表示されている

### ISSUE THREAD

**Issue by nanamagari3** [agilecommunity/oot#71]
商品名に金額が入っているため、チェックリスト画面では金額が2つ表示されている。
しかし、商品名から金額を消すと、注文画面で商品価格が表示されない。

**Comment by nobiinu-and** [comment]
商品名と、金額の扱い方があいまいなのが問題。

## なぜ商品名に金額を入れるのか?
フェアで値引きした場合に、元の金額とと値引き額、値引き後の金額を利用者に見せたいから。 (700円の20円引きで、680円だった場合、 700円, 20円, 680円を見せたい)

## なぜ金額を登録する必要があるのか?
合計金額を計算するために、商品ごとの金額が必要だから。(割引後の価格が分かればよい)

## どうした方がよさそうか?
通常価格と割引額を入れられるようにした方がいい感じ。
注文画面には、通常価格と割引額と、割引後の価格が表示できる。
注文表には割引額の総額も表示できるようになる。

**Comment by nobiinu-and** [comment]
モデルに注文通常価格と、注文割引額を追加する。
モデルに注文額は、上記2つの値から計算する。
商品名には、商品の名前しか入れないようにする。

こんなものかな。

**Comment by nobiinu-and** [comment]
値引き後の価格を英語でなんていうのかで詰まった。 sales price? retail price?
誰かつっこんでくれないかなぁとつぶやいてみたけれども。

**Comment by nobiinu-and** [comment]
某マイケルと、某Kiroに教えてもらえた。 reduced price, selling price とのこと。
英和辞典で出てくる用法はたまに間違ってることがあるらしいので、注意だって…orz

**Comment by nobiinu-and** [comment]
定価と、割引、実売ということで、 fixedOnOrder, discountOnOrder, reducedOnOrder ということにする。
うへー。フィールド名を変えるのか…orz

**Comment by nobiinu-and** [comment]
あー。疲れた…。初Directiveに挑戦。ちょっとだけ仕組みを理解した。
