### ISSUE TITLE
自分のパスワードをリセットしたい

### ISSUE THREAD

**Issue by nobiinu-and** [agilecommunity/oot#99]
忘れちゃった場合の対処。

**Comment by hideakihal** [comment]
SecureSocialを使っているので、/resetへのリンクを作るのはどうでしょうか？

**Comment by nobiinu-and** [comment]
なるほど。いいですね!!
routingを直してあげればできるかな??

**Comment by hideakihal** [comment]
ソースコードを見ると、SecureSocialのビューをAngularJS側で独自のビューに置き換えているので、ビューの作成が必要そうですね。
あと、routesもAngularJS側で制御しているので追加が必要だと思います。

Play側のroutesに/resetの設定は一部あるみたいですが、/resetにアクセスしても{email:null}が返ってくるだけでした。

http://securesocial.ws/guide/installation.html
